[tool.poetry]
name = "juleplayliste"
version = "0.1.0"
description = ""
authors = ["Henrik Gregersen <support@allekankode.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
